pipeline:
  name: gcp-ci
  identifier: gcpci
  projectIdentifier: Harnessci
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnector
        build: <+input>
  stages:
    - stage:
        name: Build and Push docker image to artifact
        identifier: Build_and_Push_docker_image_to_artifact
        description: "Build the image and push it to GCR"
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushGCR
                  name: BuildAndPushGCR_1
                  identifier: BuildAndPushGCR_1
                  spec:
                    connectorRef: gcrconnector
                    host: us-central1-docker.pkg.dev/samad-450009/sam-gcr
                    projectID: samad-450009
                    imageName: app
                    tags:
                      - ${trigger.commitSha}
                    caching: true
                  outputs:
                    - name: IMAGE_TAG
                      value: ${trigger.commitSha}
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikube
              namespace: dev
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
