apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/samad-450009/sam-gcr/samad-450009/app:19
        name: todo-app
        ports:
        - containerPort: 8080
